const TICKER_EXCLUSIONS = new Set([
  "100K", "150K", "1B", "200DMA", "200K", "20K", "23K", "350K", "400K", "401K",
  "4K", "5E6572", "70K", "7K", "80K", "ACB", "ACC", "ADVD", "AFAIK", "AG",
  "AGAIN", "AGE", "AI", "AJ", "AL", "ALL", "ALMOST", "ALPHA", "AM", "AMA",
  "AND", "ANOVA", "ANY", "AP", "AS", "ASK", "ASSET", "ASSETS", "AUM", "BB",
  "BETA", "BMS", "BRK", "BS", "BSU", "BTP", "BW", "CAGE", "CAGR", "CAIA",
  "CANADA", "CAP", "CAT", "CCPC", "CEF", "CELFX", "CET", "CGT", "CI", "CIO",
  "CLASS", "CLI", "CMA", "COVID", "CPA", "CPP", "CRA", "CRSP", "CSI", "CSIF",
  "CT", "CTA", "CTAP", "CW", "DB", "DBI", "DCA", "DCPP", "DEGIRO", "DEV",
  "DHUP", "DIY", "DMB", "DMS", "DO", "DOH", "DSP", "DTT", "DUNN", "DWA",
  "EE", "EMIMI", "EMTV", "ENC", "EQUITY", "ER", "ERP", "ESTATE", "ETFS", "ETN",
  "EVER", "EWG2", "EX", "FAANG", "FACTOR", "FAQ", "FAR", "FDIC", "FF", "FF6",
  "FFFF", "FHSA", "FI", "FIRE", "FIXED", "FU", "FWIW", "FWT", "FYI", "GALAXY",
  "GAM", "GB", "GBL", "GBP", "GDP", "GF", "GIA", "GLOBAL", "GME", "GOOGL",
  "GP", "GTD", "GTV", "HELOC", "HRP", "HST", "HTML", "IAG", "ICAPM", "ICE",
  "IE", "IKBR", "IMHO", "IMWO", "INCOME", "INFL1A", "IOZ", "IRA", "IRR", "IRS",
  "ISA", "ISFW", "ISIN", "ITT", "JGB", "KID", "KIID", "KISS", "KLP", "LARGE",
  "LCV", "LESS", "LHA", "LMP", "LTCG", "LTT", "M1", "MAY", "MB", "MBA",
  "MJPRU", "MKT", "ML", "MTH", "MTN", "MWRR", "NA", "NASDAQ", "NAT", "NAV",
  "NCP", "NEW", "NOBODY", "NOK", "NONE", "NOT", "NSTI", "NSTX", "NT", "NTS",
  "OAS", "OK", "OLS", "OMX", "OOP", "OP", "OSC", "P2P", "PE", "PIMCO",
  "PM", "PREMIA", "PTX", "PURE", "PV", "QT", "QUANT", "RAEF", "RAGF", "RBC",
  "RE", "RIGHT", "RISK", "RMW", "RRR", "SC", "SCG", "SEK", "SHOULD", "SIFMA",
  "SIPP", "SLEEVE", "SMALL", "SMLK", "SOFI", "SONIA", "SPI", "SPX", "SRRIX", "SS",
  "STATUS", "STI", "STIIAM", "STOXX", "STRAT", "STRIPS", "SUPER", "SV", "SWR", "TARGET",
  "TEV", "THIS", "TIA", "TIAA", "TICKER", "TILTS", "TMOM", "TODO", "TOT", "TOTAL",
  "TRAD", "TREND", "TSM", "TSMC", "TSMOM", "TSP", "TWS", "UCAP", "UCIT", "UCTIS",
  "UI", "UP", "USD10Y", "VALUE", "VBAL", "VDHG", "VGAD", "VGE", "VHCOL", "VIDEO",
  "VIRTUS", "VIU", "VIX", "VP", "VSTAX", "VTSIAX", "VUSA", "VUSXX", "WEIGHT", "WMA",
  "WML", "WORK", "WSL", "XIRR", "YIELD", "YMMV", "YR", "YTD", "ZB", "ZEM",
  "ZF", "ZFL",
]);
