const TICKER_EXCLUSIONS = new Set([
  "10B", "10K", "13F", "200DMA", "200K", "20K", "23K", "2B", "300M", "400K",
  "401K", "4K", "50M", "5X", "7AM", "7K", "80K", "8AMEST", "ACB", "ACC",
  "ADJ76", "ADVD", "AFAIK", "AG", "AGAIN", "AGE", "AI", "AJ", "AL", "ALL",
  "ALMOST", "ALPHA", "AM", "AMA", "AND", "ANOVA", "ANY", "AP", "ASK", "ASSET",
  "ASSETS", "AUM", "BB", "BETA", "BMS", "BRK", "BS", "BSU", "BTP", "BW",
  "CAGR", "CAIA", "CANADA", "CAP", "CAT", "CEF", "CELFX", "CET", "CGT", "CI",
  "CIO", "CLASS", "CLI", "CMA", "COVID", "CPA", "CPP", "CRA", "CRSP", "CSI",
  "CSIF", "CT", "CTA", "CTAP", "CW", "DB", "DBI", "DCA", "DCPP", "DEGIRO",
  "DEV", "DHUP", "DIY", "DMB", "DMS", "DO", "DOH", "DSP", "DTT", "DUNN",
  "EE", "EMIMI", "EMTV", "ENC", "EQUITY", "ER", "ERP", "ESTATE", "ETFS", "ETN",
  "EVER", "EX", "F4RATK", "FAANG", "FACTOR", "FAQ", "FAR", "FDIC", "FF", "FF3",
  "FFFF", "FHSA", "FI", "FIRE", "FIXED", "FU", "FWIW", "FWT", "FYI", "GALAXY",
  "GAM", "GB", "GBL", "GBP", "GDP", "GF", "GIA", "GLOBAL", "GME", "GOOGL",
  "GP", "GTD", "GTV", "HELOC", "HRP", "HST", "HTML", "IAG", "ICAPM", "IE",
  "IMHO", "IMWO", "INCOME", "IOZ", "IRA", "IRR", "IRS", "ISA", "ISFW", "ISIN",
  "ITT", "JGB", "KID", "KIID", "KISS", "KLP", "LARGE", "LCV", "LESS", "LHA",
  "LMP", "LTCG", "LTT", "M1", "MAY", "MB", "MBA", "MJPRU", "MKT", "MTH",
  "MTN", "MWRR", "NA", "NASDAQ", "NAV", "NEW", "NOBODY", "NOK", "NONE", "NOT",
  "NSTI", "NSTX", "NT", "NTS", "OAS", "OK", "OLS", "OMX", "OOP", "OP",
  "OSC", "PE", "PIMCO", "PM", "PMO205", "PREMIA", "PTX", "PURE", "PV", "QT",
  "QUANT", "R2", "RAEF", "RAGF", "RBC", "RE", "RIGHT", "RISK", "RMW", "RRR",
  "SC", "SEK", "SHOULD", "SIFMA", "SIPP", "SLEEVE", "SMALL", "SOFI", "SONIA", "SPX",
  "SRRIX", "SS", "STATUS", "STI", "STIIAM", "STOXX", "STRAT", "STRIPS", "SUPER", "SV",
  "SWR", "TARGET", "THIS", "TIA", "TIAA", "TICKER", "TILTS", "TMOM", "TODO", "TOT",
  "TOTAL", "TREND", "TSM", "TSMC", "TSMOM", "TSP", "TWS", "UCAP", "UCIT", "UCTIS",
  "UI", "UP", "VALUE", "VBAL", "VDHG", "VGAD", "VGE", "VHCOL", "VIRTUS", "VIX",
  "VP", "VSTAX", "VTSIAX", "VUSXX", "WEIGHT", "WMA", "WML", "WORK", "WSL", "XIRR",
  "YIELD", "YR", "YTD", "ZB", "ZEM", "ZF", "ZFL",
]);
