const TICKER_EXCLUSIONS = new Set([
  "1C", "1M", "1Y", "25M", "27M", "2X", "316M", "3M", "3X", "40M",
  "7STN", "ACB", "ACC", "AGAIN", "AGE", "AI", "AL", "ALL", "ALMOST", "ALPHA",
  "AM", "AMA", "AND", "AP", "ASK", "ASSET", "ASSETS", "AUM", "B8TI", "BB",
  "BETA", "BMS", "BRK", "BSU", "BTP", "C25", "CAGR", "CANADA", "CAP", "CAT",
  "CELFX", "CGT", "CI", "CLASS", "CMA", "COVID", "CPP", "CRA", "CSI", "CT",
  "CTA", "CTAP", "CW", "DB", "DBI", "DCA", "DEV", "DFA223", "DFA227", "DFA391",
  "DFA600", "DIY", "DMB", "DMS", "DO", "DSP", "DUNN", "EE", "EMIMI", "EMTV",
  "ENC", "EQUITY", "ER", "ESTATE", "ESTX50", "ETFS", "EVER", "EX", "FACTOR",
  "FAQ", "FAR", "FF", "FF5", "FHSA", "FI", "FIRE", "FIXED", "FR10Y", "FU",
  "FWT", "G3B", "G7", "GALAXY", "GAM", "GBL", "GBP", "GER5Y", "GF", "GIA",
  "GLOBAL", "GOOGL", "GP", "GTD", "GTV", "HELOC", "HRP", "HTML", "IAG", "IE",
  "IMWO", "INCOME", "IRA", "IRR", "IRS", "ISA", "ISFW", "ISIN", "ITT", "JD1991",
  "JGB", "JP10Y", "KLP", "LARGE", "LMP", "LTCG", "LTT", "MAY", "MB", "MKT",
  "MTH", "MTN", "NA", "NASDAQ", "NOBODY", "NOK", "NONE", "NSTI", "NSTX", "NT",
  "NTS", "OAS", "OMX", "OMXC25", "PE10", "PM", "PREMIA", "PURE", "PV", "QUANT",
  "R6", "RAEF", "RAGF", "RBC", "RBF636", "RE", "RIGHT", "RISK", "RMW", "SC",
  "SEK", "SHOULD", "SIPP", "SLEEVE", "SMALL", "SOFI", "SONIA", "SP500", "SPX", "SRRIX",
  "STATUS", "STI", "STIIAM", "STOXX", "STRAT", "SV", "SWR", "TARGET", "THIS", "TIA",
  "TIAA", "TICKER", "TILTS", "TMOM", "TOT", "TOTAL", "TREND", "TSM", "TSMOM", "TSP",
  "UCTIS", "VALUE", "VBAL", "VHCOL", "VIRTUS", "VIX", "VSTAX", "VTSIAX", "VUSXX", "WEIGHT",
  "WIG40", "WMA", "WML", "WORK", "YIELD", "YR", "YTD", "ZF",
]);
