// Database of known ETF and fund tickers
// Auto-updated by scripts/update_tickers.py
const TICKER_DB = {
  // ---  ---
  "AAVM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ABRVX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ACWI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ACWIS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ACWV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ADA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AGG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AGGG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AHLIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AHLT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AIMOX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ALTS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AMFAX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AOA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "APEX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ARCIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ASFYX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVCG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVDE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVDV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVEE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVEG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVEM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVES": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVEU": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVGC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVGE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVGS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVGV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVIG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVIV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVMA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVNM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVNV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVRE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVSC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVSG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVUQ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVUS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVUV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVWC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "AVWS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "BAB": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "BCOM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "BDMIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "BLDG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "BLNDX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "BND": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "BOND": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "BOXX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "BTAL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "BTC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "BTGD": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CAD": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CAOS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CAPE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CASH": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CBIL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CBYYX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CEMR": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CEMU": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CMCI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CORE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "COSIC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CPI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CRRY": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "CTA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DAX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DBMF": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DBMFE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DBPE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DBPG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DCAM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DCOR": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DEGC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DEGT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DEMGX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DEMR": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFAC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFAE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFAI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFAT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFAW": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFAX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFEM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFEV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFFVX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFGP": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFIC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFIV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFIVX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFJ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFSV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFSVX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DFUS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DGS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DGSD": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DIHP": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DISV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DTLA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DUHP": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DXIV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "DXUV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ECB": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EDC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EDV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EIMI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EIPCX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EMGF": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EMXC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ESE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ESG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EUNK": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EUNL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EUNZ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EUR": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EURL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EWG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EWJV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EXUS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "EYLD": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FBTC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FEM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FEMS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FLKR": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FLTR": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FLXE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FLXI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FNBGX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FNDE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FOMO": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FRDM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FREM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FSKAX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FSMAX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FSPSX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FTIHX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FUD": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FXAIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FYLD": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FZILX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "FZROX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "GDE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "GLD": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "GLDM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "GLTL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "GOOG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "GOVZ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "GVAL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "HFGM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "HIDE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "HIGH": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "HYSA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IAUM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IBCI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IBCZ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IBIT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IDEV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IDMO": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IEF": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IEFA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IEMA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IEMG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IEMO": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IGLA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "II": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IMAE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IMGP": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IMIE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IMOM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IMTM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "INDEX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "INTL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IQEA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ISCF": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ITOT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IUSQ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IVAL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IWDA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IWDS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IWFM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IWHC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "IWMO": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "JEPI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "JOGS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "JPGL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "JPLG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "JPY": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "KMLM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "LCG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "LCSIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "LVWC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "LYOR": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "MATE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "MFUT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "MID": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "MOM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "MVOL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "MWRE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "NKE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "NTSG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "NTSI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "NTSX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "NTSZ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "PDBC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "PQTIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "PRAR": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "PRAZ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "PSRU": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QDSIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QGMIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QHFIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QLEIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QLENX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QLFIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QMHIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QMHNX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QMJ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QMNIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QMOM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QNZIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QRPIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QRPNX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QSPIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "QVAL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RAUS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "REAL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "REMIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RERGX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RESP": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RPV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RQP": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RQR": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RQS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RQT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RSBA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RSBT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RSBY": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RSSB": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RSST": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RSSX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "RSSY": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SCHP": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SGOV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SMB": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SPIA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SPPW": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SPUU": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SPY": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SPYI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SSGLX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SUB": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SVIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SWRD": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SXRV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "SYLD": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "TAIL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "TAT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "TCIEX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "TDTF": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "TEQLX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "TEST": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "TIPS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "TLDR": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "TMF": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "TOPIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "TQQQ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "UEQC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "UEQV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "UGL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "UIQN": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "UNH": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "UPRO": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "URTH": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "USD": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VAB": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VAGE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VBIL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VBMPX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VCN": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VDET": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VDIPX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VEA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VEMIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VEQT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VERE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VFMF": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VFMO": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VFORX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VGGX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VGIT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VGLT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VGRO": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VGSH": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VGSNX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VGVF": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VGWL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VIIIX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VJPA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VMATX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VMIG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VMO": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VMOT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VNQ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VNQI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VOE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VONE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VOO": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VSMPX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VTI": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VTIP": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VTV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VUG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VUN": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VVL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VWCE": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VWCG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VWO": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VWRA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VWRL": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VXC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VXF": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "VXUS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "WEBN": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "WIG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "WORLD": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "WPEA": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "WSML": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "WTED": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XAW": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XDBC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XDEB": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XDEM": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XDEQ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XDEV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XEC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XEF": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XEON": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XEQT": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XGDU": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XIC": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XIU": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XNAS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "XUU": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ZAG": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ZCN": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ZCS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ZFS": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ZLB": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ZPRV": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ZPRX": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },
  "ZROZ": { name: "", category: "", family: "", expenseRatio: null, totalAssets: null },

  // --- Defined Outcome ---
  "TEND": { name: "Ishares Large Cap 10% Target Buffer Dec ETF", category: "Defined Outcome", family: "iShares", expenseRatio: 0.5, totalAssets: 49117232 },

  // --- Diversified Emerging Mkts ---
  "DEHP": { name: "Dimensional Emerging Markets High Profitability ETF", category: "Diversified Emerging Mkts", family: "Dimensional Fund Advisors", expenseRatio: 0.41, totalAssets: 383261696 },
  "EEMV": { name: "iShares MSCI Emerging Markets Min Vol Factor ETF", category: "Diversified Emerging Mkts", family: "iShares", expenseRatio: 0.25, totalAssets: 3427418880 },
  "FM": { name: "iShares Inc.", category: "Diversified Emerging Mkts", family: "iShares", expenseRatio: 0.2, totalAssets: 189171104 },
  "PIE": { name: "Invesco Dorsey Wright Emerging Markets Momentum ETF", category: "Diversified Emerging Mkts", family: "Invesco", expenseRatio: 0.9, totalAssets: 160742880 },
  "PXH": { name: "Invesco RAFI Emerging Markets ETF", category: "Diversified Emerging Mkts", family: "Invesco", expenseRatio: 0.47, totalAssets: 1980352000 },

  // --- ETF ---
  "AYEM": { name: "iShares MSCI EM IMI Screened UCITS ETF USD (Acc)", category: "ETF", family: "BlackRock Asset Management Ireland - ETF", expenseRatio: 0.18, totalAssets: 8030799872 },
  "C10": { name: "Amundi ETF Govt Bond EuroMTS Broad Investment Grade 10-15 UCITS ETF", category: "ETF", family: "Amundi Asset Management", expenseRatio: null, totalAssets: 91531000 },
  "CAPM": { name: "CAPITAL GROUP MULTI SEC INCOME ", category: "ETF", family: "Capital International Asset Mngmt (Canada)", expenseRatio: null, totalAssets: 243983376 },
  "EMIM": { name: "iShares Core MSCI EM IMI ETF USD Acc", category: "ETF", family: "BlackRock Asset Management Ireland - ETF", expenseRatio: 0.25, totalAssets: 10115028992 },
  "EMMV": { name: "Ossiam Lux - Ossiam Emerging Markets Minimum Variance NR", category: "ETF", family: "", expenseRatio: null, totalAssets: null },
  "EMVL": { name: "iShares Edge MSCI EM Value Factor UCITS ETF USD (Acc)", category: "ETF", family: "BlackRock Asset Management Ireland - ETF", expenseRatio: 0.4, totalAssets: 1470787072 },
  "EUNM": { name: "iShares MSCI EM UCITS ETF USD (Acc)", category: "ETF", family: "BlackRock Asset Management Ireland - ETF", expenseRatio: 0.18, totalAssets: 8626567168 },
  "EUNN": { name: "iShares Core MSCI Japan IMI UCITS ETF USD (Acc)", category: "ETF", family: "BlackRock Asset Management Ireland - ETF", expenseRatio: 0.15, totalAssets: null },
  "EUPE": { name: "Ossiam Shiller Barclays Cape Europe Sector Value TR UCITS ETF 1C EUR Acc", category: "ETF", family: "OSSIAM", expenseRatio: 0.65, totalAssets: 159969248 },
  "GARP": { name: "iShares Trust - iShares MSCI USA Quality GARP ETF", category: "ETF", family: "", expenseRatio: null, totalAssets: null },
  "HBB": { name: "Global X Canadian Select Universe Bond Index Corporate Class ETF", category: "ETF", family: "Global X Investments Canada Inc.", expenseRatio: 0.09, totalAssets: 3654854400 },
  "HXDM": { name: "Global X Intl Developed Markets Equity Index Corporate Class ETF", category: "ETF", family: "Global X Investments Canada Inc.", expenseRatio: 0.2, totalAssets: 1061675840 },
  "HXS": { name: "Global X S&P 500 Corporate Class ETF", category: "ETF", family: "Global X Investments Canada Inc.", expenseRatio: 0.1, totalAssets: 5794298880 },
  "HXT": { name: "Global X S&P/TSX 60 Corporate Class ETF", category: "ETF", family: "Global X Investments Canada Inc.", expenseRatio: 0.07, totalAssets: 4868896768 },
  "IWVL": { name: "iShares Edge MSCI World Value Factor UCITS ETF USD (Acc)", category: "ETF", family: "BlackRock Asset Management Ireland - ETF", expenseRatio: 0.3, totalAssets: 6449653248 },
  "MVEU": { name: "iShares Edge MSCI Europe Minimum Volatility UCITS ETF EUR (Acc)", category: "ETF", family: "BlackRock Asset Management Ireland - ETF", expenseRatio: 0.25, totalAssets: 857326400 },
  "NFLX": { name: "Netflix, Inc.", category: "ETF", family: "", expenseRatio: null, totalAssets: null },
  "PMIF": { name: "PIMCO Monthly Income ETF", category: "ETF", family: "PIMCO Canada", expenseRatio: null, totalAssets: null },
  "PSRW": { name: "Invesco RAFI All-World Fundamental Value UCITS ETF", category: "ETF", family: "Invesco Investment Management Limited", expenseRatio: null, totalAssets: 225214352 },
  "SGAJ": { name: "iShares MSCI Japan Screened UCITS ETF USD (Acc)", category: "ETF", family: "BlackRock Asset Management Ireland - ETF", expenseRatio: 0.15, totalAssets: 2693820928 },
  "SXR1": { name: "iShares VII PLC - iShares Core MSCI Pac ex-Jpn ETF USD Acc", category: "ETF", family: "BlackRock Asset Management Ireland - ETF", expenseRatio: 0.2, totalAssets: 3831222528 },
  "USSC": { name: "State Street SPDR MSCI USA Small Cap Value Weighted UCITS ETF USD Acc", category: "ETF", family: "State Street Global Advisors Europe Limited", expenseRatio: 0.3, totalAssets: 923133248 },
  "VGEK": { name: "Vanguard FTSE Developed Asia Pacific ex Japan UCITS ETF USD Accumulation", category: "ETF", family: "Vanguard Group (Ireland) Limited", expenseRatio: null, totalAssets: 3273871616 },

  // --- Foreign Large Blend ---
  "ACWX": { name: "iShares MSCI ACWI ex U.S. ETF", category: "Foreign Large Blend", family: "iShares", expenseRatio: 0.32, totalAssets: 9512109056 },
  "IXUS": { name: "iShares Core MSCI Total International Stock ETF", category: "Foreign Large Blend", family: "iShares", expenseRatio: 0.07, totalAssets: 57611653120 },

  // --- Foreign Large Value ---
  "PXF": { name: "Invesco RAFI Developed Markets ex-U.S. ETF", category: "Foreign Large Value", family: "Invesco", expenseRatio: 0.43, totalAssets: 2760992000 },

  // --- Foreign Small/Mid Value ---
  "PDN": { name: "Invesco RAFI Developed Markets ex-U.S. Small-Mid ETF", category: "Foreign Small/Mid Value", family: "Invesco", expenseRatio: 0.47, totalAssets: 402997312 },

  // --- Global Bond ---
  "WIP": { name: "SPDR FTSE International Government Inflation-Protected Bond ETF", category: "Global Bond", family: "State Street Investment Management", expenseRatio: 0.5, totalAssets: 412437440 },

  // --- Global Bond-USD Hedged ---
  "BNDX": { name: "Vanguard Total International Bond Index Fund", category: "Global Bond-USD Hedged", family: "Vanguard", expenseRatio: 0.07, totalAssets: 118794993664 },

  // --- High Yield Bond ---
  "ANGL": { name: "VanEck Fallen Angel High Yield Bond ETF", category: "High Yield Bond", family: "VanEck", expenseRatio: 0.25, totalAssets: 3160542464 },

  // --- Inflation-Protected Bond ---
  "LTPZ": { name: "PIMCO 15+ Year U.S. TIPS Index Exchange-Traded Fund", category: "Inflation-Protected Bond", family: "PIMCO", expenseRatio: 0.2, totalAssets: 687412992 },

  // --- Intermediate Core-Plus Bond ---
  "VBND": { name: "Vident U.S. Bond Strategy ETF", category: "Intermediate Core-Plus Bond", family: "Vident Financial", expenseRatio: 0.41, totalAssets: 506955488 },

  // --- Large Blend ---
  "DFAU": { name: "Dimensional US Core Equity Market ETF", category: "Large Blend", family: "Dimensional Fund Advisors", expenseRatio: 0.12, totalAssets: 10698257408 },
  "ROE": { name: "Astoria US Equal Weight Quality Kings ETF", category: "Large Blend", family: "Astoria Portfolio Advisors LLC", expenseRatio: 0.49, totalAssets: 223144016 },
  "VIG": { name: "Vanguard Dividend Appreciation Index Fund ETF Shares", category: "Large Blend", family: "Vanguard", expenseRatio: 0.04, totalAssets: 123750858752 },

  // --- Large Value ---
  "AVLV": { name: "Avantis US Large Cap Value ETF", category: "Large Value", family: "Avantis Investors", expenseRatio: 0.15, totalAssets: 10633122816 },
  "IUSV": { name: "iShares Core S&P U.S. Value ETF", category: "Large Value", family: "iShares", expenseRatio: 0.04, totalAssets: 24990392320 },
  "PRF": { name: "Invesco RAFI US 1000 ETF", category: "Large Value", family: "Invesco", expenseRatio: 0.34, totalAssets: 9044963328 },

  // --- Long Government ---
  "TYA": { name: "Simplify Intermediate Term Treasury Futures Strategy ETF", category: "Long Government", family: "Simplify Asset Management", expenseRatio: 0.25, totalAssets: 66164272 },

  // --- MUTUALFUND ---
  "AAPL": { name: "15994", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "AVDVX": { name: "Avantis International Small Cap Val Ins", category: "MUTUALFUND", family: "", expenseRatio: 0.36, totalAssets: 648829952 },
  "AVUVX": { name: "Avantis U.S. Small Cap Value Instl", category: "MUTUALFUND", family: "", expenseRatio: 0.25, totalAssets: 1463442304 },
  "BRSIX": { name: "Bridgeway Ultra-Small Company Market", category: "MUTUALFUND", family: "", expenseRatio: 0.75, totalAssets: 130594544 },
  "CD": { name: "1", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "CSV": { name: "Corporación Financiera Alba, S.A.", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "DFCEX": { name: "DFA Emerging Markets Core Equity 2 I", category: "MUTUALFUND", family: "", expenseRatio: 0.39, totalAssets: 37862424576 },
  "DFEVX": { name: "DFA Emerging Markets Value I", category: "MUTUALFUND", family: "", expenseRatio: 0.44, totalAssets: 14324404224 },
  "DFJSX": { name: "DFA Japanese Small Company I", category: "MUTUALFUND", family: "", expenseRatio: 0.4, totalAssets: 222402512 },
  "DFQTX": { name: "DFA US Core Equity 2 I", category: "MUTUALFUND", family: "", expenseRatio: 0.18, totalAssets: 36733157376 },
  "DFSTX": { name: "DFA US Small Cap I", category: "MUTUALFUND", family: "", expenseRatio: 0.27, totalAssets: 18427858944 },
  "DGEIX": { name: "DFA Global Equity I", category: "MUTUALFUND", family: "", expenseRatio: 0.25, totalAssets: 11071971328 },
  "DISVX": { name: "DFA International Small Cap Value Portfolio", category: "MUTUALFUND", family: "", expenseRatio: 0.43, totalAssets: 15322270720 },
  "DWA": { name: "919514", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "EST": { name: "3908", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "FDGRX": { name: "Fidelity Growth Company Fund", category: "MUTUALFUND", family: "", expenseRatio: 0.69, totalAssets: 82479603712 },
  "FF6": { name: "First Cash Financial Services Inc.", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "FISMX": { name: "Fidelity International Small Cap", category: "MUTUALFUND", family: "", expenseRatio: 0.9, totalAssets: 5880058368 },
  "FISVX": { name: "Fidelity Small Cap Value Index", category: "MUTUALFUND", family: "", expenseRatio: 0.05, totalAssets: 1864838784 },
  "FP": { name: "First Person Ltd", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "FSGGX": { name: "Fidelity Global ex US Index", category: "MUTUALFUND", family: "", expenseRatio: 0.055, totalAssets: 18667124736 },
  "FSSNX": { name: "Fidelity Small Cap Index", category: "MUTUALFUND", family: "", expenseRatio: 0.025, totalAssets: 30093862912 },
  "FXNAX": { name: "Fidelity U.S. Bond Index", category: "MUTUALFUND", family: "", expenseRatio: 0.025, totalAssets: 70381690880 },
  "IAF": { name: "4001", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "III": { name: "3i Group Plc", category: "MUTUALFUND", family: "", expenseRatio: 0.0, totalAssets: 8387333632 },
  "LONG": { name: "135921", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "MC": { name: "12620", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "ML": { name: "MERCATOR MINERALS LTD.", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "NCP": { name: "11895", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "RRC": { name: "Regency Centers Corporation", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "SCG": { name: "SCANA Corporation", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "SPI": { name: "Sappi Limited", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "TON": { name: "Toho Holdings Co., Ltd.", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "VIU": { name: "VIVUS Inc.", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "VTMGX": { name: "Vanguard Developed Markets Index Admiral", category: "MUTUALFUND", family: "", expenseRatio: 0.05, totalAssets: 307323502592 },
  "VTS": { name: "83760", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "WFE": { name: "Long Run Exploration Ltd.", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },
  "WS": { name: "Arizona Mining Inc.", category: "MUTUALFUND", family: "", expenseRatio: null, totalAssets: null },

  // --- Mid-Cap Blend ---
  "IJH": { name: "iShares Core S&P Mid-Cap ETF", category: "Mid-Cap Blend", family: "iShares", expenseRatio: 0.05, totalAssets: 111657140224 },

  // --- Mid-Cap Value ---
  "IVOV": { name: "Vanguard S&P Mid-Cap 400 Value Index Fund ETF Shares", category: "Mid-Cap Value", family: "Vanguard", expenseRatio: 0.1, totalAssets: 1366149504 },
  "VFVA": { name: "Vanguard U.S. Value Factor ETF Shares", category: "Mid-Cap Value", family: "Vanguard", expenseRatio: 0.13, totalAssets: 790495360 },

  // --- Miscellaneous Region ---
  "EGPT": { name: "VanEck ETF Trust", category: "Miscellaneous Region", family: "VanEck", expenseRatio: 1.24, totalAssets: 20318928 },
  "EIDO": { name: "iShares MSCI Indonesia ETF", category: "Miscellaneous Region", family: "iShares", expenseRatio: 0.59, totalAssets: 310150976 },
  "EPHE": { name: "iShares MSCI Philippines ETF", category: "Miscellaneous Region", family: "iShares", expenseRatio: 0.59, totalAssets: 187502080 },
  "EWW": { name: "iShares MSCI Mexico ETF", category: "Miscellaneous Region", family: "iShares", expenseRatio: 0.5, totalAssets: 2596836608 },
  "ICOL": { name: "iShares MSCI Colombia ETF", category: "Miscellaneous Region", family: "iShares", expenseRatio: 0.61, totalAssets: 20476504 },
  "NGE": { name: "Global X MSCI Nigeria ETF", category: "Miscellaneous Region", family: "Global X Funds", expenseRatio: 0.8, totalAssets: 11163358 },
  "PAK": { name: "Global X MSCI Pakistan ETF", category: "Miscellaneous Region", family: "Global X Funds", expenseRatio: 0.8, totalAssets: 28349530 },
  "TUR": { name: "iShares MSCI Turkey ETF", category: "Miscellaneous Region", family: "iShares", expenseRatio: 0.59, totalAssets: 346330432 },

  // --- Multi-Asset Leveraged ---
  "NTSE": { name: "WisdomTree Emerging Markets Efficient Core Fund", category: "Multi-Asset Leveraged", family: "WisdomTree", expenseRatio: 0.32, totalAssets: 50947736 },

  // --- Muni National Long ---
  "SMI": { name: "VanEck HIP Sustainable Muni ETF", category: "Muni National Long", family: "VanEck", expenseRatio: 0.24, totalAssets: 11168753 },

  // --- Real Estate ---
  "REIT": { name: "ALPS Active REIT ETF", category: "Real Estate", family: "ALPS", expenseRatio: 0.68, totalAssets: 49978580 },

  // --- Short-Term Bond ---
  "VCSH": { name: "Vanguard Short-Term Corporate Bond Index Fund ETF Shares", category: "Short-Term Bond", family: "Vanguard", expenseRatio: 0.03, totalAssets: 48297553920 },

  // --- Small Blend ---
  "PRFZ": { name: "Invesco RAFI US 1500 Small-Mid ETF", category: "Small Blend", family: "Invesco", expenseRatio: 0.34, totalAssets: 2736197376 },

  // --- Small Value ---
  "DIV": { name: "Global X SuperDividend U.S. ETF", category: "Small Value", family: "Global X Funds", expenseRatio: 0.45, totalAssets: 737139456 },
  "IJS": { name: "iShares S&P Small-Cap 600 Value ETF", category: "Small Value", family: "iShares", expenseRatio: 0.18, totalAssets: 7580123136 },
  "SLYV": { name: "State Street SPDR S&P 600 Small Cap Value ETF", category: "Small Value", family: "State Street Investment Management", expenseRatio: 0.15, totalAssets: 4333981184 },
  "VBR": { name: "Vanguard Small-Cap Value Index Fund ETF Shares", category: "Small Value", family: "Vanguard", expenseRatio: 0.05, totalAssets: 64184619008 },
  "VIOV": { name: "Vanguard S&P Small-Cap 600 Value Index Fund ETF Shares", category: "Small Value", family: "Vanguard", expenseRatio: 0.1, totalAssets: 1714642560 },

  // --- Trading--Inverse Equity ---
  "DRIP": { name: "Direxion Daily S&P Oil & Gas Exp. & Prod. Bear 2X Shares", category: "Trading--Inverse Equity", family: "Direxion Funds", expenseRatio: 1.01, totalAssets: 44956764 },

  // --- Trading--Leveraged Debt ---
  "TYD": { name: "Direxion Daily 7-10 Year Treasury Bull 3X Shares", category: "Trading--Leveraged Debt", family: "Direxion Funds", expenseRatio: 1.07, totalAssets: 45449800 },

  // --- Trading--Leveraged Equity ---
  "DDM": { name: "ProShares Ultra Dow30", category: "Trading--Leveraged Equity", family: "ProShares", expenseRatio: 0.95, totalAssets: 509179392 },
  "SSO": { name: "ProShares Ultra S&P500", category: "Trading--Leveraged Equity", family: "ProShares", expenseRatio: 0.87, totalAssets: 6769420800 },

  // --- Trading--Miscellaneous ---
  "SVXY": { name: "ProShares Short VIX Short-Term Futures ETF", category: "Trading--Miscellaneous", family: "ProShares", expenseRatio: 0.95, totalAssets: 192006080 },
  "VIXY": { name: "ProShares VIX Short-Term Futures ETF", category: "Trading--Miscellaneous", family: "ProShares", expenseRatio: 0.95, totalAssets: 242680176 },

  // --- Utilities ---
  "VPU": { name: "Vanguard Utilities Index Fund ETF Shares", category: "Utilities", family: "Vanguard", expenseRatio: 0.09, totalAssets: 11029460992 },

};
